image: registry.splentity.com/openblox/ci-build-environment/ob:latest

build:
  script:
    - ./prepare_ci.sh
    - ./autoconf.sh
    - mkdir artifacts
    - ./configure --with-libopenblox=./libopenblox.pc
    - make
