image: registry.splentity.com/openblox/ci-build-environment/ob:latest

build:
  script:
    - bash prepare_ci.sh
    - ls
    - ./autoconf.sh
    - mkdir artifacts
    - ./configure --prefix=$(readlink -f artifacts)
    - make
    - make install
    - cp libopenblox.pc artifacts
